WorkBundle\Entity\Emp:
    type: entity
    table: null
    repositoryClass: WorkBundle\Repository\EmpRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fio:
            type: string
            length: 255
        pos:
            type: integer
        salary:
            type: integer
        date:
            type: datetime

    manyToOne:
            position:
                targetEntity: WorkBundle\Entity\Position
                inversedBy: emp
                joinColumn:
                    name: pos
                    referencedColumnName: id

    lifecycleCallbacks: {  }
