WorkBundle\Entity\Position:
    type: entity
    table: null
    oneToMany:
            employee:
                targetEntity: WorkBundle\Entity\Employee
                mappedBy: position
    oneToOne:
            position:
                targetEntity: WorkBundle\Entity\Position
                joinColumn:
                    name: parent_id
                    referencedColumnName: id
                    onDelete: CASCADE
    repositoryClass: WorkBundle\Repository\PositionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
        parentId:
            type: integer
            column: parent_id
            nullable: true
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
