WorkBundle\Entity\Search:
      type: entity
      table: null
      id:
          id:
              type: integer
              id: true
              generator:
                  strategy: AUTO
      fields:
          field:
            type: string
            length: 255
      lifecycleCallbacks: {  }