employee_index:
    path:     /
    defaults: { _controller: "WorkBundle:Employee:index" }
    methods:  [GET, POST]

employee_show:
    path:     /{id}/show
    defaults: { _controller: "WorkBundle:Employee:show" }
    methods:  GET

employee_new:
    path:     /new
    defaults: { _controller: "WorkBundle:Employee:new" }
    methods:  [GET, POST]

employee_edit:
    path:     /{id}/edit
    defaults: { _controller: "WorkBundle:Employee:edit" }
    methods:  [GET, POST]

employee_delete:
    path:     /{id}/delete
    defaults: { _controller: "WorkBundle:Employee:delete" }
    methods:  DELETE

employee_search:
    path:     /search
    defaults: { _controller: "WorkBundle:Employee:search" }
    methods:  [GET, POST]

employee_getajax:
    path:     /getajax
    defaults: { _controller: "WorkBundle:Employee:getajax" }
    methods:  GET

employee_ajaxsearch:
    path:     /ajaxsearch/{text}
    defaults: { _controller: "WorkBundle:Employee:ajaxsearch" }
    methods: [GET, POST]