work_employee:
        resource: "@WorkBundle/Resources/config/routing/employee.yml"
        prefix:   /employee

work_homepage:
    path:           /
    defaults:       { _controller: WorkBundle:Default:index }

work_list:
    path:           /list
#    prefix:   /list
    defaults:       { _controller: WorkBundle:Default:list }

work_view:
    path:           /view/{id}
    defaults:       { _controller: WorkBundle:Default:view }
    requirements:
              id:   \d+

work_set:
    path:           /set
    defaults:       { _controller: WorkBundle:Default:set }

work_about:
    path:           /about
    defaults:       { _controller: WorkBundle:Default:about }